#!/bin/sh

awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Recommended | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Recommended
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Most-Popular | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Most-Popular
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-One | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-One
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Two | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Two
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Three | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Three
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Four | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Four
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-News | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-News
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/CBeebies | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/CBeebies
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/CBBC | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/CBBC
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Arts | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Arts
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Comedy | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Comedy
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Documentaries | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Documentaries
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Dramas-and-Soaps | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Dramas-and-Soaps
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Entertainment | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Entertainment
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Films | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Films
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-History | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-History
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Lifestyle | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Lifestyle
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Music | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Music
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Science-and-Nature | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Science-and-Nature
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Sport | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Sport
awk -F/ '{ s=$8; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Audio-Described | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Audio-Described
awk -F/ '{ s=$8; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Signed | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Signed
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Northern-reland | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Northern-reland
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Scotland | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Scotland
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/BBC-Parliament | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/BBC-Parliament
awk -F/ '{ s=$7; gsub("-", " ", s); print s; print}' < /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/tmp/S4C | sed 's/#.*//' | awk '!x[$0]++' > /usr/lib/enigma2/python/Plugins/Extensions/BBC-iPlayer-Recorder/stream-list/S4C
exit
